name: brackets
description: Lean markup representation and rendering.
version: 1.0.0
repository: https://github.com/purplenoodlesoop/brackets

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  purple_lints: any
  test: ^1.24.0
